### ISSUE TITLE
`gollum-site generate` fails with stacktrace

### ISSUE THREAD

**Issue by sol** [dreverri/gollum-site#25]
```
$ gollum-site generate
/home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:18:in `find': wrong number of arguments (4 for 2) (ArgumentError)
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/wiki.rb:201:in `page'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/wiki.rb:212:in `paged'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:457:in `find_page_from_name'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:404:in `process_page_link_tag'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:262:in `process_tag'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:228:in `block (2 levels) in process_tags'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:227:in `gsub!'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:227:in `block in process_tags'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:220:in `each'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:220:in `process_tags'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/markup.rb:71:in `render'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-2.2.3/lib/gollum/page.rb:203:in `formatted_data'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:92:in `formatted_data'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:53:in `generate'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:87:in `block in generate'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:85:in `each'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:85:in `generate'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/gems/gollum-site-0.1.11/bin/gollum-site:116:in `<top (required)>'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/bin/gollum-site:19:in `load'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/bin/gollum-site:19:in `<main>'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
        from /home/sol/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by stoicflame** [comment]
I'm seeing the same issue. Any report of progress?

**Comment by acamilo** [comment]
same problem
''''
$ gollum-site generate
/var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:227:in `find': wrong number of arguments (4 for 2) (ArgumentError)
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:227:in`page'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:238:in `paged'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:423:in`find_page_from_name'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:364:in `process_page_link_tag'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:222:in`process_tag'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:188:in `process_tags'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:187:in`gsub!'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:187:in `process_tags'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:180:in`each'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:180:in `process_tags'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:71:in`render'
    from /var/lib/gems/1.8/gems/gollum-2.4.11/lib/gollum/page.rb:225:in `formatted_data'
    from /var/lib/gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/page.rb:92:in`formatted_data'
    from /var/lib/gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/page.rb:53:in `generate'
    from /var/lib/gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:87:in`generate'
    from /var/lib/gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:85:in `each'
    from /var/lib/gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:85:in`generate'
    from /var/lib/gems/1.8/gems/gollum-site-0.1.11/bin/gollum-site:116
    from /var/lib/gems/1.8/bin/gollum-site:19:in `load'
    from /var/lib/gems/1.8/bin/gollum-site:19
''''

**Comment by bwellhoefer** [comment]
$ gollum-site generate
/Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:227:in `find': wrong number of arguments (4 for 2) (ArgumentError)
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:227:in`page'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:238:in `paged'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:423:in`find_page_from_name'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:364:in `process_page_link_tag'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:222:in`process_tag'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:188:in `process_tags'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:187:in`gsub!'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:187:in `process_tags'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:180:in`each'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:180:in `process_tags'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:71:in`render'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/page.rb:225:in `formatted_data'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/page.rb:92:in`formatted_data'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/page.rb:53:in `generate'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:87:in`generate'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:85:in `each'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:85:in`generate'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/gollum-site:116
    from /usr/bin/gollum-site:23:in `load'
    from /usr/bin/gollum-site:23

**Comment by bwellhoefer** [comment]
This issue happens after a fresh layout import and running "generate" without committing the imported files or without using "--working"

**Comment by funcktub** [comment]
With me the issue happens on a 100% commited repro regardless of wether I'm using "--working" or not:

/var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:18:in `find': wrong number of arguments (4 for 2) (ArgumentError)
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/wiki.rb:227:in`page'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/wiki.rb:238:in `paged'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:423:in`find_page_from_name'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:364:in `process_page_link_tag'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:222:in`process_tag'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:188:in `block (2 levels) in process_tags'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:187:in`gsub!'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:187:in `block in process_tags'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:180:in`each'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:180:in `process_tags'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:71:in`render'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/page.rb:225:in `formatted_data'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:92:in`formatted_data'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:53:in `generate'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:87:in`block in generate'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:85:in `each'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:85:in`generate'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/bin/gollum-site:116:in `<top (required)>'
    from /usr/local/bin/gollum-site:19:in`load'
    from /usr/local/bin/gollum-site:19:in `<main>'

gollum-site --working generate
/var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:18:in `find': wrong number of arguments (4 for 2) (ArgumentError)
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/wiki.rb:227:in`page'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/wiki.rb:238:in `paged'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:423:in`find_page_from_name'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:364:in `process_page_link_tag'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:222:in`process_tag'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:188:in `block (2 levels) in process_tags'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:187:in`gsub!'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:187:in `block in process_tags'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:180:in`each'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:180:in `process_tags'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/markup.rb:71:in`render'
    from /var/lib/gems/1.9.1/gems/gollum-2.4.5/lib/gollum/page.rb:225:in `formatted_data'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:92:in`formatted_data'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/page.rb:53:in `generate'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:87:in`block in generate'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:85:in `each'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/lib/gollum-site/site.rb:85:in`generate'
    from /var/lib/gems/1.9.1/gems/gollum-site-0.1.11/bin/gollum-site:116:in `<top (required)>'
    from /usr/local/bin/gollum-site:19:in`load'
    from /usr/local/bin/gollum-site:19:in `<main>'

**Comment by mpemer** [comment]
same here - details below, including relevant versions.

```
(0) testgollum [master]$ gollum-site generate
/Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:227:in `find': wrong number of arguments (4 for 2 (ArgumentError)
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:227:in `page'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/wiki.rb:238:in `paged'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:423:in `find_page_from_name'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:364:in `process_page_link_tag'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:222:in `process_tag'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:188:in `process_tags'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:187:in `gsub!'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:187:in `process_tags'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:180:in `each'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:180:in `process_tags'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/markup.rb:71:in `render'
    from /Library/Ruby/Gems/1.8/gems/gollum-2.4.11/lib/gollum/page.rb:225:in `formatted_data'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/page.rb:92:in `formatted_data'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/page.rb:53:in `generate'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:87:in `generate'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:85:in `each'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/../lib/gollum-site/site.rb:85:in `generate'
    from /Library/Ruby/Gems/1.8/gems/gollum-site-0.1.11/bin/gollum-site:116
    from /usr/bin/gollum-site:23:in `load'
    from /usr/bin/gollum-site:23
```
