### ISSUE TITLE
gollum-site generate fails

### ISSUE THREAD

**Issue by lottspot** [dreverri/gollum-site#33]
I did see issue #25, but the stacktrace I received is very different from the stacktrace received by the users in that issue is quite different from this stack trace, so it seemed reasonable to assume they are separate issues.

Anyhow, I was just trying to replicate the example from the README.md step by step, and when I got to the gollum-site generate step, I encountered this set of errors.

Any help which can be offered is greatly appreciated, as I'm very hopeful to use gollum-site for my primary site platform!

```
[lottspot-smeagol /home/private]$ git clone git://github.com/radiant/radiant.wiki.git
Cloning into 'radiant.wiki'...
remote: Counting objects: 2355, done.
remote: Compressing objects: 100% (2320/2320), done.
remote: Total 2355 (delta 1357), reused 7 (delta 4)
Receiving objects: 100% (2355/2355), 432.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1357/1357), done.
[lottspot-smeagol /home/private]$ cd radiant.wiki/
[lottspot-smeagol /home/private/radiant.wiki]$ gollum-site generate
/home/private/.gem/ruby/2.0.0/gems/blankslate-3.1.2/lib/blankslate.rb:51: warning: undefining `object_id' may cause serious problems
/home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:127:in `block (2 levels) in init_pack': pack /home/private/radiant.wiki/.git/objects/pack/pack-6b9aa3131d2a0172b74ce7b85289beff8bc385a5.pack has discontinuous index 1 (Grit::GitRuby::Internal::PackFormatError)
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:124:in `times'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:124:in `block in init_pack'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:70:in `with_idx'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:122:in `init_pack'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:45:in `initialize'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:763:in `new'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:763:in `block (2 levels) in load_packs'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:761:in `each'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:761:in `block in load_packs'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:760:in `open'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:760:in `load_packs'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:743:in `initpacks'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:89:in `get_raw_object_by_sha1'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:334:in `walk_log'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:287:in `log'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:306:in `rev_list'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `block in rev_list'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:224:in `block in try_run'
        from /home/private/local/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:223:in `try_run'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `rev_list'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/commit.rb:121:in `find_all'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/grit-2.4.1/lib/grit/repo.rb:406:in `commit'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:31:in `prepare'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:82:in `generate'
        from /home/private/local/lib/ruby/gems/2.0.0/gems/gollum-site-0.1.12/bin/gollum-site:116:in `<top (required)>'
        from /home/private/local/bin/gollum-site:23:in `load'
        from /home/private/local/bin/gollum-site:23:in `<main>'
[lottspot-smeagol /home/private/radiant.wiki]$
```

**Comment by lottspot** [comment]
Also, I forgot to mention, this is being run on FreeBSD 9.1

**Comment by patrickwelker** [comment]
Seems to be a common issue, not only when running FreeBSD. Maybe this would help as a fix:  https://github.com/pat/thinking-sphinx/pull/380

**Comment by rahul286** [comment]
If you are using ruby 2.0 or above, `grit` will not work. It is not maintained anymore - https://github.com/mojombo/grit

I solved this for me using older ruby version (1.9.3) in my case.

If you use RVM, see: https://github.com/dreverri/gollum-site/issues/37#issuecomment-46623836

**Comment by jhannwong** [comment]
Is this project going to use gitlab_grit instead?
