### ISSUE TITLE
gollum-site generate fails because of grit

### ISSUE THREAD

**Issue by rahul286** [dreverri/gollum-site#37]
I got following when running `gollum-site generate`

I think grit needs to be replaced by https://github.com/libgit2/rugged as grit is no longer maintained. 

```
gollum-site generate                                                                [18:06:08]
/Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:108:in `unpack_object_header_gently': undefined method `>>' for "x":String (NoMethodError)
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:56:in `get_raw_object'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:32:in `[]'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:84:in `block in get_raw_object_by_sha1'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:83:in `each'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:83:in `get_raw_object_by_sha1'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:334:in `walk_log'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:287:in `log'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:306:in `rev_list'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `block in rev_list'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby.rb:224:in `block in try_run'
    from /Users/rahul286/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:91:in `block in timeout'
    from /Users/rahul286/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:35:in `block in catch'
    from /Users/rahul286/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:35:in `catch'
    from /Users/rahul286/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:35:in `catch'
    from /Users/rahul286/.rvm/rubies/ruby-head/lib/ruby/2.2.0/timeout.rb:106:in `timeout'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby.rb:223:in `try_run'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `rev_list'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/commit.rb:121:in `find_all'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/grit-2.4.1/lib/grit/repo.rb:406:in `commit'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:31:in `prepare'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:82:in `generate'
    from /Users/rahul286/.rvm/gems/ruby-head/gems/gollum-site-0.1.12/bin/gollum-site:116:in `<top (required)>'
    from /Users/rahul286/.rvm/gems/ruby-head/bin/gollum-site:23:in `load'
    from /Users/rahul286/.rvm/gems/ruby-head/bin/gollum-site:23:in `<main>'
    from /Users/rahul286/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
    from /Users/rahul286/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rahul286** [comment]
In my case, I used old ruby (thanks to rvm.io)

```
rvm install 1.9.3 --create
rvm --ruby-version use 1.9.3
```

May be above instructions could be added to readme file till the issue gets fixed.
