### ISSUE TITLE
Liquid error: pack has discontinuous index 1

### ISSUE THREAD

**Issue by pberto** [dreverri/gollum-site#41]
I used to be able to use gollum-site but now I am getting this error. On MacOSX.

Any hint?

**Comment by Gottox** [comment]
Same error here:

```
# sudo gem install gollum-site
# gollum-site import
The default layout has been imported. Don't forget to commit these changes.
# gollum-site generate
/usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:127:in `block (2 levels) in init_pack': pack /home/tox/dev/src/documentation.wiki/.git/objects/pack/pack-599b36bf68d4b20af4a619da54658397a7690cbc.pack has discontinuous index 1 (Grit::GitRuby::Internal::PackFormatError)
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:124:in `times'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:124:in `block in init_pack'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:70:in `with_idx'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:122:in `init_pack'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:45:in `initialize'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:763:in `new'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:763:in `block (2 levels) in load_packs'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:761:in `each'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:761:in `block in load_packs'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:760:in `open'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:760:in `load_packs'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:743:in `initpacks'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:89:in `get_raw_object_by_sha1'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:334:in `walk_log'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:287:in `log'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:306:in `rev_list'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `block in rev_list'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:224:in `block in try_run'
    from /usr/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    from /usr/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
    from /usr/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    from /usr/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    from /usr/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:223:in `try_run'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `rev_list'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/commit.rb:121:in `find_all'
    from /usr/lib/ruby/gems/2.2.0/gems/grit-2.4.1/lib/grit/repo.rb:406:in `commit'
    from /usr/lib/ruby/gems/2.2.0/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:31:in `prepare'
    from /usr/lib/ruby/gems/2.2.0/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:82:in `generate'
    from /usr/lib/ruby/gems/2.2.0/gems/gollum-site-0.1.12/bin/gollum-site:116:in `<top (required)>'
    from /usr/bin/gollum-site:23:in `load'
    from /usr/bin/gollum-site:23:in `<main>'
```

I used [this wiki](https://github.com/voidlinux/documentation/wiki) to test

System: VoidLinux
Arch: x86_64

**Comment by pberto** [comment]
It would be really great to have a solution here.

**Comment by pberto** [comment]
Ok it's because of grit. Now it works if using Ruby < 2.0. Pretty annoying.
